### PR TITLE
Additional status bar format options

### LINKED ISSUE #151: Side panel fails to update when running time entry has no project
Steps to reproduce:
- Start a time entry in Toggl with no project
- Reload Obsidian (or unload and reload the plugin)

Expected result:
- The side panel loads properly.

Actual result:
- The side panel fails to load (though it shows the correct time of the running time entry at first, and the status bar continues to update):

image

The console generates the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at Array.create_if_block_15 (plugin:obsidian-toggl-integration:21915:34)
    at Object.p (plugin:obsidian-toggl-integration:22326:104)
    at update (plugin:obsidian-toggl-integration:12880:32)
    at flush (plugin:obsidian-toggl-integration:12851:7)
```

Sadly, Svelte is a bit out of my depth for now.

MacOS Sonoma 14.1.1, Obsidian 1.4.13, Obsidian Toggl Integration 0.11.0.

### PR DESCRIPTION
**Pull request by leoccyao**
An easy improvement, since the setting already exists. Code for handing numbers very similar to https://github.com/liamcain/obsidian-calendar-plugin/blob/master/src/settings.ts#L108-L122

Also removes a duplicate initiation of a status bar item (which has been creating additional spacing in the status bar)

Edit: also closes #151

### CODE REVIEW

**Comment by leoccyao** [comment]
Added a number more options for formatting the status bar. Increases the rate at which the status bar text is updated to once per second, though the Toggl API is still polled at the previous rate of every 6 seconds.

Also ran into the source of the bug for #151 while working on project in status bar! Closes #151

**Comment by mcndt** [comment]
Hi Leo, thanks for your PRs (also #149)!! I really appreciate other people building together on this. 

I'm a bit in a slow mode when it comes to maintaining my Obsidian plugins, but I will try to take some time out of my schedule the next week or two to properly review and test your code, so that it can merge to `main` and ship to plugin users.

**Comment by leoccyao** [comment]
Just wondering if there's any update on when my contribution can be reviewed!

File: lib/config/PluginSettings.ts [hunk 1]
```diff
@@ -11,15 +11,31 @@ export interface PluginSettings {
...
+  /**
+   * The prefix to show before the time entry in the status bar.
+   */
+  statusBarPrefix?: string;
+
+  /** Whether to show the project in the status bar. */
+  statusBarShowProject?: boolean;
+
+  /** Message shown in the status bar when no time entry is running. */
+  statusBarNoEntryMesssage?: string;
```
Comment (mcndt) [inline lib/config/PluginSettings.ts:40]: Personally I don't see a need to customise something like this, can you elaborate on your use case?

File: lib/config/PluginSettings.ts [hunk 2]
```diff
@@ -11,15 +11,31 @@ export interface PluginSettings {
...
+   * The time format for the status bar.
+   */
+  statusBarFormat?: string;
 
-  /** Update the day's total time in real-time in the sidebar */
-  updateInRealTime?: boolean;
+  /**
+   * The prefix to show before the time entry in the status bar.
+   */
+  statusBarPrefix?: string;
```
Comment (mcndt) [inline lib/config/PluginSettings.ts:34]: Personally I don't see a need to customise something like this, can you elaborate on your use case?

File: lib/util/millisecondsToTimeString.ts [hunk 3]
```diff
@@ -1,15 +1,18 @@
...
-  const sec = Math.round((ms / 1000) % 60);
-  const min = Math.floor((ms / 1000 / 60) % 60);
-  const hr = Math.floor(ms / 1000 / 60 / 60);
+import moment from "moment";
+import "moment-duration-format";
 
-  return `${hr}:${min < 10 ? "0" + min : min}:${sec < 10 ? "0" + sec : sec}`;
+export default function millisecondsToTimeString(ms: number): string {
+  // @ts-expect-error
+  return moment.duration(ms).format(
```
Comment (mcndt) [inline lib/util/millisecondsToTimeString.ts:6]: Great that we can use a proper library for this now instead of my clunky methods :)

Is there a reason why you couldn't fix the type error? I don't like using `ts-expect-error` unless there's absolutely no other way around it.

(Same for the function below)

Comment (mcndt) [reply lib/util/millisecondsToTimeString.ts:6]: I see that type defs are available for this library, would that solve it?
https://www.npmjs.com/package/@types/moment-duration-format

File: lib/toggl/TogglService.ts [hunk 4]
```diff
@@ -278,11 +291,18 @@ export default class TogglService {
         )}...`;
       }
       const duration = this.getTimerDuration(this._currentTimeEntry);
-      const minutes = Math.floor(duration / 60);
-      const time_string = `${minutes} minute${minutes != 1 ? "s" : ""}`;
+      // @ts-expect-error
```
Comment (mcndt) [inline lib/toggl/TogglService.ts:294]: Same remark about the `ts-expect-error` as above.

**Review by mcndt — COMMENTED** [review]
Looks pretty good! If you make a few changes I will release this one as well. 

Promise I won't leave you hanging for weeks this time!

I'll hold off on releasing 0.12.0 for a moment in case you can resolve this PR this week, then I can bundle the changes together.

File: lib/config/PluginSettings.ts (hunk 1 above)
Comment (leoccyao) [reply lib/config/PluginSettings.ts:40]: Default setting: "-"
I currently have it set to "No time entry running"; I can imagine others may prefer a different message or for it to be completely blank (hiding the status bar entry when no time entry is running).

File: lib/config/PluginSettings.ts (hunk 2 above)
Comment (leoccyao) [reply lib/config/PluginSettings.ts:34]: Default setting: "Timer: "
I currently have it set to blank (the empty string) to save a bit of space in the status bar. I can imagine others may prefer different messages such as "Time entry: ".

File: lib/util/millisecondsToTimeString.ts (hunk 3 above)
Comment (leoccyao) [reply lib/util/millisecondsToTimeString.ts]: Installing with `npm i --save-dev @types/moment-duration-format` immediately gets rid of the `ts-expect-error` directives!

File: lib/toggl/TogglService.ts (hunk 4 above)
Comment (leoccyao) [reply lib/toggl/TogglService.ts]: Resolved as above!

**Comment by mcndt** [comment]
LGTM, merging this into master and making a release today. Thanks for your contributions!!
I'll try to stay a bit more on top if it now so don't hesitate if you have more ideas for PRs.
